management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8090
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    tomcat:
      initial-size: 1
  jpa:
    properties:
      hibernate:
        hibernate.format_sql: true
        jdbc:
          lob.non_contextual_creation: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: create-drop
    format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
