management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8090
kafka:
  topic: test_hdfs
  server: 192.168.0.17:9092
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    tomcat:
      initial-size: 1
